### PR TITLE
Deploy process

### PR DESCRIPTION
**Pull request by paulsonnentag**
implements #70 deployment

This turned out to be a little bit more complicated than I thought. 2 main problems:
- Github pages doesn't support routing with historyAPI well
- Sheet router doesn't support hash routing well

I ended up using [surge.sh](surge.sh) which allows to easily deploy static pages for free Yay!

@H3rby7 @timgrossmann you should have received an email, so you can create signup credentials

Deployment is very easy, just run:

```
npm run deploy
```

The page is the published as https://robotopia.surge.sh

### CODE REVIEW

**Review by timgrossmann — APPROVED** [review]

**Comment by timgrossmann** [comment]
@paulsonnentag Nope, no email 😉

**Comment by paulsonnentag** [comment]
Have you checked your hdm email?

**Comment by timgrossmann** [comment]
@paulsonnentag Yes, no new Emails

**Comment by pguth** [comment]
Having it on GH-Pages would be nice nonetheless. That service is there to stay.

**Pull request merged**
